#!/usr/bin/env bash
# Run each experiment and commit its results immediately, so a reclaimed
# container never loses completed work.
cd "$(dirname "$0")/.."
for cfg in "$@"; do
  echo "=== START ${cfg} $(date -u +%H:%M:%S)"
  if python3 experiments/run_experiment.py --config "configs/${cfg}.yaml" --quiet; then
    git add -A
    git commit -q -m "Add ${cfg} experiment results (30 seeds)

Generated by experiments/run_experiment.py from configs/${cfg}.yaml.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01Cm7dRv9xmcRoxnrDXju2yf" || true
    echo "=== DONE ${cfg} $(date -u +%H:%M:%S)"
  else
    echo "=== FAILED ${cfg} $(date -u +%H:%M:%S)"
  fi
done
echo "ALL_DONE"
